# Generated by Django 5.0 on 2024-03-04 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='AC',
            new_name='ac',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='AC',
            new_name='ac',
        ),
    ]
